[package]
name = "rocket-test-bug"
version = "0.1.0"
authors = ["Knut Nesheim <knutin@gmail.com>"]
edition = "2018"

[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket" }
rocket_contrib = { git = "https://github.com/SergioBenitez/Rocket", features = ["postgres_pool"] }